[options]
addons_path = /home/fnet/odoo19/munoth_v19/odoo/addons,/home/fnet/odoo19/munoth_v19/addons,/home/fnet/odoo19/munoth_v19/custom/enterprise_addons,/home/fnet/odoo19/munoth_v19/custom/addons
admin_passwd = admin123
db_host = localhost
db_maxconn = 5
db_user = odoo19
db_password = admin
db_port = 5436
http_port = 8013
without_demo = all

; ---- Reduced footprint - test_odoo_server.conf already using most cores ----
workers = 2
max_cron_threads = 1

limit_time_cpu = 3600
limit_time_real = 7200
limit_time_real_cron = -1

limit_memory_soft = 1073741824
limit_memory_hard = 1610612736

limit_request = 8192
log_level = info