[options]
addons_path = /home/ubuntu/odoo/munoth_v19/odoo/addons,/home/ubuntu/odoo/munoth_v19/addons,/home/ubuntu/odoo/munoth_v19/custom/enterprise_addons,/home/ubuntu/odoo/munoth_v19/custom/addons
admin_passwd = admin123
db_host = localhost
db_maxconn = 64
db_user = odoo_19
db_password = admin
db_port = 5432
http_port = 8019
without_demo = all
