[options]
addons_path = /home/ubuntu/odoo/munoth_v19/odoo/addons,/home/ubuntu/odoo/munoth_v19/addons,/home/ubuntu/odoo/munoth_v19/custom/enterprise_addons,/home/ubuntu/odoo/munoth_v19/custom/addons
admin_passwd = admin@123

db_host = localhost
db_port = 5432
db_user = odoo19
db_password = admin
db_maxconn = 16
db_template = template0

http_port = 8019
http_interface = 0.0.0.0
proxy_mode = False

log_level = warn

workers = 0
max_cron_threads = 1
limit_memory_hard = 4294967296
limit_memory_soft = 3221225472
limit_request = 8192
limit_time_cpu = 120
limit_time_real = 300
limit_time_real_cron = -1

list_db = True
server_wide_modules = base,web
without_demo = True

smtp_server = localhost
smtp_port = 25
smtp_ssl = False

csv_internal_sep = ,
unaccent = False
transient_age_limit = 1.0