[options]
addons_path = /home/fnet/odoo19/munoth_v19/odoo/addons,/home/fnet/odoo19/munoth_v19/addons,/home/fnet/odoo19/munoth_v19/custom/enterprise_addons,/home/fnet/odoo19/munoth_v19/custom/addons
admin_passwd = admin@123
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = admin
db_maxconn = 64
db_name = False
db_template = template0
db_sslmode = prefer
dbfilter =
http_enable = True
http_interface =
http_port = 8013
longpolling_port = 8072
proxy_mode = False
log_level = warn
log_handler = :WARNING
log_db = False
log_db_level = warning
logfile = /var/log/odoo/odoo19.log
syslog = False
workers = 4
max_cron_threads = 1
limit_memory_hard = 4294967296
limit_memory_soft = 3221225472
limit_request = 8192
limit_time_cpu = 120
limit_time_real = 300
limit_time_real_cron = -1
list_db = True
server_wide_modules = base,web
demo = {}
without_demo = True
email_from = False
smtp_server = localhost
smtp_port = 25
smtp_ssl = False
smtp_user = False
smtp_password = False
csv_internal_sep = ,
unaccent = False
transient_age_limit = 1.0